#pragma once

#include <unordered_set>
#include <cstdint>
#include <map>
#include <string>

enum SSL {
    DTLSv10 = 0xfeff,
    DTLSv12 = 0xfefd,
    DTLSv13 = 0xfefc
};

inline std::map<uint16_t, std::string> TLS_VERSION_MAPPER = {
    {0x0002, "s2"},
    {0x0300, "s3"},
    {0x0301, "10"},
    {0x0302, "11"},
    {0x0303, "12"},
    {0x0304, "13"},
    {SSL::DTLSv10, "d1"},
    {SSL::DTLSv12, "d2"},
    {SSL::DTLSv13, "d3"},
};

inline std::unordered_set<uint16_t> TLS_GREASE_TYPES = {
    0x0a0a, 0x1a1a, 0x2a2a, 0x3a3a,
    0x4a4a, 0x5a5a, 0x6a6a, 0x7a7a,
    0x8a8a, 0x9a9a, 0xaaaa, 0xbaba,
    0xcaca, 0xdada, 0xeaea, 0xfafa
};

enum SSLExtension {
    SSL_EXTENSION_SERVER_NAME = 0,
    SSL_EXTENSION_MAX_FRAGMENT_LENGTH = 1,
    SSL_EXTENSION_CLIENT_CERTIFICATE_URL = 2,
    SSL_EXTENSION_TRUSTED_CA_KEYS = 3,
    SSL_EXTENSION_TRUNCATED_HMAC = 4,
    SSL_EXTENSION_STATUS_REQUEST = 5,
    SSL_EXTENSION_USER_MAPPING = 6,
    SSL_EXTENSION_CLIENT_AUTHZ = 7,
    SSL_EXTENSION_SERVER_AUTHZ = 8,
    SSL_EXTENSION_CERT_TYPE = 9,
    SSL_EXTENSION_SUPPORTED_GROUPS = 10,
    SSL_EXTENSION_EC_POINT_FORMATS = 11,
    SSL_EXTENSION_SRP = 12,
    SSL_EXTENSION_SIGNATURE_ALGORITHMS = 13,
    SSL_EXTENSION_USE_SRTP = 14,
    SSL_EXTENSION_HEARTBEAT = 15,
    SSL_EXTENSION_APPLICATION_LAYER_PROTOCOL_NEGOTIATION = 16,
    SSL_EXTENSION_STATUS_REQUEST_V2 = 17,
    SSL_EXTENSION_SIGNED_CERTIFICATE_TIMESTAMP = 18,
    SSL_EXTENSION_CLIENT_CERTIFICATE_TYPE = 19,
    SSL_EXTENSION_SERVER_CERTIFICATE_TYPE = 20,
    SSL_EXTENSION_PADDING = 21,
    SSL_EXTENSION_ENCRYPT_THEN_MAC = 22,
    SSL_EXTENSION_EXTENDED_MASTER_SECRET = 23,
    SSL_EXTENSION_TOKEN_BINDING = 24,
    SSL_EXTENSION_CACHED_INFO = 25,
    SSL_EXTENSION_TLS_LTS = 26,
    SSL_EXTENSION_COMPRESS_CERTIFICATE = 27,
    SSL_EXTENSION_RECORD_SIZE_LIMIT = 28,
    SSL_EXTENSION_PWD_PROTECT = 29,
    SSL_EXTENSION_PWD_CLEAR = 30,
    SSL_EXTENSION_PASSWORD_SALT = 31,
    SSL_EXTENSION_TICKET_PINNING = 32,
    SSL_EXTENSION_TLS_CERT_WITH_EXTERN_PSK = 33,
    SSL_EXTENSION_DELEGATED_CREDENTIAL = 34,
    SSL_EXTENSION_SESSIONTICKET_TLS = 35,
    SSL_EXTENSION_TLMSP = 36,
    SSL_EXTENSION_TLMSP_PROXYING = 37,
    SSL_EXTENSION_TLMSP_DELEGATE = 38,
    SSL_EXTENSION_SUPPORTED_EKT_CIPHERS = 39,
    SSL_EXTENSION_KEY_SHARE_OLD = 40,
    SSL_EXTENSION_PRE_SHARED_KEY = 41,
    SSL_EXTENSION_EARLY_DATA = 42,
    SSL_EXTENSION_SUPPORTED_VERSIONS = 43,
    SSL_EXTENSION_COOKIE = 44,
    SSL_EXTENSION_PSK_KEY_EXCHANGE_MODES = 45,
    SSL_EXTENSION_TICKETEARLYDATAINFO = 46,
    SSL_EXTENSION_CERTIFICATE_AUTHORITIES = 47,
    SSL_EXTENSION_OID_FILTERS = 48,
    SSL_EXTENSION_POST_HANDSHAKE_AUTH = 49,
    SSL_EXTENSION_SIGNATURE_ALGORITHMS_CERT = 50,
    SSL_EXTENSION_KEY_SHARE = 51,
    SSL_EXTENSION_TRANSPARENCY_INFO = 52,
    SSL_EXTENSION_CONNECTION_ID_DEPRECATED = 53,
    SSL_EXTENSION_CONNECTION_ID = 54,
    SSL_EXTENSION_EXTERNAL_ID_HASH = 55,
    SSL_EXTENSION_EXTERNAL_SESSION_ID = 56,
    SSL_EXTENSION_QUIC_TRANSPORT_PARAMETERS = 57,
    SSL_EXTENSION_TICKET_REQUEST = 58,
    SSL_EXTENSION_DNSSEC_CHAIN = 59,
    SSL_EXTENSION_SEQUENCE_NUMBER_ENCRYPTION_ALGORITHMS = 60,
    SSL_EXTENSION_RRC = 61,
    SSL_EXTENSION_TLS_FLAGS = 62,
    SSL_EXTENSION_NEXT_PROTOCOL_NEGOTIATION = 13172,
    SSL_EXTENSION_ORIGIN_BOUND_CERTIFICATES = 13175,
    SSL_EXTENSION_ENCRYPTED_CLIENT_CERTIFICATES = 13180,
    SSL_EXTENSION_APPLICATION_SETTING = 17513,
    SSL_EXTENSION_CHANNEL_ID = 30031,
    SSL_EXTENSION_CHANNEL_ID_NEW = 30032,
    SSL_EXTENSION_PADDING_TEMP = 35655,
    SSL_EXTENSION_ECH_OUTER_EXTENSION = 64768,
    SSL_EXTENSION_ENCRYPTED_CLIENT_HELLO = 65037,
    SSL_EXTENSION_RENEGOTIATION_INFO = 65281
};
