name: windows-build
on:
  push:
    branches: [main]
    paths: [wireshark/*, wireshark/source/*, wireshark/build-scripts/*, .github/workflows/*]
  workflow_dispatch:

jobs:
  wireshark-windows:
    name: build
    runs-on: windows-2022
    env:
      PLATFORM: x64
      WIRESHARK_BASE_DIR: C:\Development
      CMAKE_PREFIX_PATH: D:\a\wireshark\Qt\6.2.3\msvc2019_64
      WIRESHARK_VERSION_EXTRA: -GithubActionBuild
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cache directory
        run: mkdir "C:\choco"

      - name: cache
        uses: actions/cache@v3
        with:
          path: C:\choco
          key:  C:\choco

      - name: Set Chocolatey cache location
        run: choco config set cacheLocation "C:\choco"

      - name: checkout wireshark
        run: cd wireshark/build-scripts/ && "C:\Program Files\Git\bin\git.exe" clone -o upstream --branch wireshark-4.4.0 https://gitlab.com/wireshark/wireshark.git --depth=500

      - name: Choco install
        run: choco install -y asciidoctorj xsltproc docbook-bundle nsis winflexbison3 cmake
      - name: Install strawberryperl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.30'
          distribution: strawberry
            #- name: Add msbuild to PATH
          #uses: microsoft/setup-msbuild@v2
          #with:
          #vs-version: 16.8
          #- name: Mkdir
          #run: mkdir build
          #- name: Cmake
          #run: cmake -DCMAKE_SYSTEM_VERSION="10.0.20348.0" -A x64 ..
          #env:
          #PLATFORM: x64
          #WIRESHARK_BASE_DIR: C:/wireshark-libs
          #QT5_BASE_DIR: C:/Qt/5.12.3/msvc2017_64
          #working-directory: build
          #- name: Build
          #run: cmake --build . --config RelWithDebInfo
          #working-directory: build

