name: windows-build
on:
  push:
    branches: [main]
    paths: [wireshark/*, wireshark/source/*, wireshark/build-scripts/*]
  workflow_dispatch:

jobs:
  wireshark-windows:
    name: build
    runs-on: windows-2022
    env:
      PLATFORM: x64
      WIRESHARK_BASE_DIR: C:\Development
      CMAKE_PREFIX_PATH: D:\a\wireshark\Qt\6.2.3\msvc2019_64
      WIRESHARK_VERSION_EXTRA: -GithubActionBuild
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v3
        with:
          path: /tmp
          key:  C:/Downloads
      - name: Set Chocolatey cache location
        run: choco config set --name="'cacheLocation'" --value="'C:/Downloads'"
      - name: Choco install
        run: choco install -y asciidoctorj
